# Generated by Django 4.2 on 2026-02-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_financial',
            field=models.BooleanField(default=False, help_text='User responsible for financial operations'),
        ),
    ]
