# Generated by Django 4.2 on 2026-02-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_plan_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default plan for new users'),
        ),
    ]
