# Generated by Django 6.0.1 on 2026-07-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço mensal personalizado, substituindo o preço do plano. Vale até ser removido pelo administrador.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='surcharge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Acréscimo pontual somado apenas à próxima cobrança gerada. É zerado automaticamente depois de gerar esse pagamento.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='surcharge_reason',
            field=models.CharField(blank=True, default='', help_text="Motivo do acréscimo (ex.: 'Projeto X'). Aparece nas notas do pagamento.", max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('PIX', 'PIX'), ('CASH', 'Dinheiro'), ('MP', 'Mercado Pago')], default='MP', max_length=10),
        ),
    ]
