# Generated by Django 4.2 on 2026-02-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
