# Generated by Django 6.0.1 on 2026-07-22 09:32

from django.db import migrations

INITIAL_QUOTES = [
    {
        "text": (
            "Seja bem-vindo(a) ao nosso sonho partilhado! Que novos e "
            "maravilhosos mundos venham até você, pelas páginas dos livros."
        ),
        "attribution": "Sonhos Literários",
        "order": 0,
    },
    {
        "text": "O clube Sonhos Literários se transforma em realidade.",
        "attribution": "29 de agosto de 2018",
        "order": 1,
    },
    {
        "text": "Em 2025 o Clube Sonhos Literários completa 7 anos.",
        "attribution": "29 de agosto de 2025",
        "order": 2,
    },
]


def seed_quotes(apps, schema_editor):
    Quote = apps.get_model("club", "Quote")
    for data in INITIAL_QUOTES:
        Quote.objects.get_or_create(text=data["text"], defaults=data)


def remove_seeded_quotes(apps, schema_editor):
    Quote = apps.get_model("club", "Quote")
    Quote.objects.filter(text__in=[q["text"] for q in INITIAL_QUOTES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_contactmessage_quote'),
    ]

    operations = [
        migrations.RunPython(seed_quotes, remove_seeded_quotes),
    ]
