"""Data-only seed list for backfill_reading_history.

65 real books read by Clube Sonhos Literários, in real chronological reading
order (index 0 = first book ever read, index 64 = most recent/planned).
Metadata (author/publisher/pages/ISBN/cover) researched from real Brazilian
editions via web search - see conversation history for verification notes.

Only the first 61 entries (index 0-60) get a Reading + Meets created by
backfill_reading_history; the last 4 (currently-being-read + future/planned)
get a Book catalog entry only.
"""

BOOKS = [
    {
        'title': 'Seis Anos Depois',
        'author_first_name': 'Harlan',
        'author_last_name': 'Coben',
        'publisher_name': 'Arqueiro',
        'pages': 272,
        'isbn': '9786555650310',
        'published_date': None,
        'cover_url': 'https://m.media-amazon.com/images/P/6555650311.01.LZZZZZZZ.jpg',
    },
    {
        'title': 'Eclipse',
        'author_first_name': 'Stephenie',
        'author_last_name': 'Meyer',
        'publisher_name': 'Intrínseca',
        'pages': 464,
        'isbn': '9788598078410',
        'published_date': '2009-01-16',
        'cover_url': 'https://m.media-amazon.com/images/P/8598078417.01.LZZZZZZZ.jpg',
    },
    {
        'title': 'Com Amor, Simon',
        'author_first_name': 'Becky',
        'author_last_name': 'Albertalli',
        'publisher_name': 'Intrínseca',
        'pages': 272,
        'isbn': '9788551003053',
        'published_date': '2018-03-09',
        'cover_url': 'https://m.media-amazon.com/images/P/8551003054.01.LZZZZZZZ.jpg',
    },
    {
        'title': 'Assassinato no Expresso do Oriente',
        'author_first_name': 'Agatha',
        'author_last_name': 'Christie',
        'publisher_name': 'HarperCollins Brasil',
        'pages': 240,
        'isbn': '9788595086784',
        'published_date': '2020-03-09',
        'cover_url': 'https://m.media-amazon.com/images/P/8595086788.01.LZZZZZZZ.jpg',
    },
    {
        'title': 'Norte e Sul',
        'author_first_name': 'Elizabeth',
        'author_last_name': 'Gaskell',
        'publisher_name': 'Martin Claret',
        'pages': 746,
        'isbn': '9788544001240',
        'published_date': '2016-08-11',
        'cover_url': 'https://m.media-amazon.com/images/P/8544001246.01.LZZZZZZZ.jpg',
    },
    {
        'title': 'Miniaturista',
        'author_first_name': 'Jessie',
        'author_last_name': 'Burton',
        'publisher_name': 'Intrínseca',
        'pages': 352,
        'isbn': '9788580578164',
        'published_date': None,
        'cover_url': 'https://m.media-amazon.com/images/P/8580578167.01.LZZZZZZZ.jpg',
    },
    {
        'title': 'A Dama das Camélias',
        'author_first_name': 'Alexandre',
        'author_last_name': 'Dumas Filho',
        'publisher_name': 'Martin Claret',
        'pages': 304,
        'isbn': '9786559100910',
        'published_date': None,
        'cover_url': 'https://m.media-amazon.com/images/P/655910091X.01.LZZZZZZZ.jpg',
    },
    {
        'title': 'Grandes Esperanças',
        'author_first_name': 'Charles',
        'author_last_name': 'Dickens',
        'publisher_name': 'Companhia das Letras',
        'pages': 704,
        'isbn': '9788563560476',
        'published_date': '2012-06-26',
        'cover_url': 'https://m.media-amazon.com/images/P/8563560476.01.LZZZZZZZ.jpg',
    },
    {
        'title': 'Mulherzinhas',
        'author_first_name': 'Louisa May',
        'author_last_name': 'Alcott',
        'publisher_name': 'Martin Claret',
        'pages': 680,
        'isbn': '9788544002124',
        'published_date': None,
        'cover_url': 'https://m.media-amazon.com/images/P/8544002129.01.LZZZZZZZ.jpg',
    },
    {
        'title': 'Frankenstein',
        'author_first_name': 'Mary',
        'author_last_name': 'Shelley',
        'publisher_name': 'DarkSide Books',
        'pages': 304,
        'isbn': '9788594540188',
        'published_date': None,
        'cover_url': 'https://m.media-amazon.com/images/P/8594540183.01.LZZZZZZZ.jpg',
    },
    {
        'title': 'Jane Eyre',
        'author_first_name': 'Charlotte',
        'author_last_name': 'Brontë',
        'publisher_name': 'Companhia das Letras',
        'pages': 712,
        'isbn': '9788582851395',
        'published_date': '2021-07-19',
        'cover_url': 'https://m.media-amazon.com/images/P/8582851391.01.LZZZZZZZ.jpg',
    },
    {
        'title': 'Orgulho e Preconceito',
        'author_first_name': 'Jane',
        'author_last_name': 'Austen',
        'publisher_name': 'Companhia das Letras',
        'pages': 576,
        'isbn': '9788563560155',
        'published_date': '2011-06-21',
        'cover_url': 'https://m.media-amazon.com/images/P/8563560158.01.LZZZZZZZ.jpg',
    },
    {
        'title': 'O Duque e Eu',
        'author_first_name': 'Julia',
        'author_last_name': 'Quinn',
        'publisher_name': 'Arqueiro',
        'pages': 288,
        'isbn': '9788580411461',
        'published_date': None,
        'cover_url': 'https://m.media-amazon.com/images/P/8580411467.01.LZZZZZZZ.jpg',
    },
    {
        'title': 'O Visconde que me Amava',
        'author_first_name': 'Julia',
        'author_last_name': 'Quinn',
        'publisher_name': 'Arqueiro',
        'pages': 304,
        'isbn': '9788580411973',
        'published_date': '2013-08-14',
        'cover_url': 'https://m.media-amazon.com/images/P/8580411971.01.L.jpg',
    },
    {
        'title': 'Um Perfeito Cavalheiro',
        'author_first_name': 'Julia',
        'author_last_name': 'Quinn',
        'publisher_name': 'Arqueiro',
        'pages': 304,
        'isbn': '9788580412390',
        'published_date': '2014-02-03',
        'cover_url': 'https://m.media-amazon.com/images/P/8580412382.01.L.jpg',
    },
    {
        'title': 'Os Segredos de Colin Bridgerton',
        'author_first_name': 'Julia',
        'author_last_name': 'Quinn',
        'publisher_name': 'Arqueiro',
        'pages': 336,
        'isbn': '9788580413076',
        'published_date': None,
        'cover_url': 'https://m.media-amazon.com/images/P/8580413079.01.L.jpg',
    },
    {
        'title': 'Para Sir Phillip, com Amor',
        'author_first_name': 'Julia',
        'author_last_name': 'Quinn',
        'publisher_name': 'Arqueiro',
        'pages': 288,
        'isbn': '9788580413625',
        'published_date': '2015-02-02',
        'cover_url': 'https://m.media-amazon.com/images/P/8580413621.01.L.jpg',
    },
    {
        'title': 'O Conde Enfeitiçado',
        'author_first_name': 'Julia',
        'author_last_name': 'Quinn',
        'publisher_name': 'Arqueiro',
        'pages': 304,
        'isbn': '9788580414400',
        'published_date': '2015-08-05',
        'cover_url': 'https://m.media-amazon.com/images/P/8580414407.01.L.jpg',
    },
    {
        'title': 'Um Beijo Inesquecível',
        'author_first_name': 'Julia',
        'author_last_name': 'Quinn',
        'publisher_name': 'Arqueiro',
        'pages': 272,
        'isbn': '9788580414851',
        'published_date': None,
        'cover_url': 'https://m.media-amazon.com/images/P/8580414857.01.L.jpg',
    },
    {
        'title': 'A Caminho do Altar',
        'author_first_name': 'Julia',
        'author_last_name': 'Quinn',
        'publisher_name': 'Arqueiro',
        'pages': 320,
        'isbn': '9788580415735',
        'published_date': '2016-06-08',
        'cover_url': 'https://m.media-amazon.com/images/P/858041573X.01.L.jpg',
    },
    {
        'title': 'E Viveram Felizes Para Sempre',
        'author_first_name': 'Julia',
        'author_last_name': 'Quinn',
        'publisher_name': 'Arqueiro',
        'pages': 256,
        'isbn': '9788580416374',
        'published_date': None,
        'cover_url': 'https://m.media-amazon.com/images/P/858041637X.01.L.jpg',
    },
    {
        'title': 'Drácula',
        'author_first_name': 'Bram',
        'author_last_name': 'Stoker',
        'publisher_name': 'L&PM Editores',
        'pages': 552,
        'isbn': '9788525408419',
        'published_date': None,
        'cover_url': 'https://m.media-amazon.com/images/P/8525408417.01.L.jpg',
    },
    {
        'title': 'As Brumas de Avalon: A Senhora da Magia',
        'author_first_name': 'Marion Zimmer',
        'author_last_name': 'Bradley',
        'publisher_name': 'Imago',
        'pages': 252,
        'isbn': '9788531210372',
        'published_date': None,
        'cover_url': 'https://m.media-amazon.com/images/P/8531210372.01.L.jpg',
    },
    {
        'title': 'As Brumas de Avalon: A Grande Rainha',
        'author_first_name': 'Marion Zimmer',
        'author_last_name': 'Bradley',
        'publisher_name': 'Imago',
        'pages': 232,
        'isbn': '9788531210389',
        'published_date': None,
        'cover_url': 'https://m.media-amazon.com/images/P/8531210380.01.L.jpg',
    },
    {
        'title': 'As Brumas de Avalon: O Gamo-Rei',
        'author_first_name': 'Marion Zimmer',
        'author_last_name': 'Bradley',
        'publisher_name': 'Imago',
        'pages': 212,
        'isbn': '9788531210396',
        'published_date': None,
        'cover_url': 'https://m.media-amazon.com/images/P/8531210399.01.L.jpg',
    },
    {
        'title': 'As Brumas de Avalon: O Prisioneiro da Árvore',
        'author_first_name': 'Marion Zimmer',
        'author_last_name': 'Bradley',
        'publisher_name': 'Imago',
        'pages': 227,
        'isbn': '9788531210402',
        'published_date': None,
        'cover_url': 'https://m.media-amazon.com/images/P/8531210402.01.L.jpg',
    },
    {
        'title': 'O Jardim Secreto',
        'author_first_name': 'Frances',
        'author_last_name': 'Hodgson Burnett',
        'publisher_name': 'DarkSide Books',
        'pages': 288,
        'isbn': '9786555980134',
        'published_date': '2021-06-16',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9786555980134-L.jpg',
    },
    {
        'title': 'A Princesinha',
        'author_first_name': 'Frances',
        'author_last_name': 'Hodgson Burnett',
        'publisher_name': 'Salamandra',
        'pages': 216,
        'isbn': '9788516099206',
        'published_date': None,
        'cover_url': 'https://coolturalblog.wordpress.com/wp-content/uploads/2015/11/a-princesinha.jpg',
    },
    {
        'title': 'O Código Da Vinci',
        'author_first_name': 'Dan',
        'author_last_name': 'Brown',
        'publisher_name': 'Sextante',
        'pages': 432,
        'isbn': '9788575421130',
        'published_date': None,
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9788575421130-L.jpg',
    },
    {
        'title': 'Morte no Nilo',
        'author_first_name': 'Agatha',
        'author_last_name': 'Christie',
        'publisher_name': 'HarperCollins Brasil',
        'pages': 320,
        'isbn': '9786555110029',
        'published_date': '2020-09-15',
        'cover_url': 'https://harpercollins.com.br/cdn/shop/files/9786555110029_1200x1200.jpg?v=1781699777',
    },
    {
        'title': 'O Fantasma da Ópera',
        'author_first_name': 'Gaston',
        'author_last_name': 'Leroux',
        'publisher_name': 'L&PM Editores',
        'pages': 336,
        'isbn': '9788525426628',
        'published_date': None,
        'cover_url': 'https://www.lpm.com.br/livros/Imagens/fantasma_da_opera_9788525426628_9788525427083_hd.jpg',
    },
    {
        'title': 'Onde Existe Amor, Deus Aí Está',
        'author_first_name': 'Leon',
        'author_last_name': 'Tolstói',
        'publisher_name': 'Verus',
        'pages': 128,
        'isbn': '9788587795212',
        'published_date': None,
        'cover_url': 'https://img.travessa.com.br/livro/BA/74/74d4b959-17b4-44b4-8f50-fdb4125d58c5.jpg',
    },
    {
        'title': 'Anne de Green Gables',
        'author_first_name': 'Lucy Maud',
        'author_last_name': 'Montgomery',
        'publisher_name': 'Nova Fronteira',
        'pages': 392,
        'isbn': '9788520943496',
        'published_date': None,
        'cover_url': 'https://img.travessa.com.br/livro/GR/a7/a75dad23-82aa-465c-aae1-1eac595054b7.jpg',
    },
    {
        'title': 'O Corcunda de Notre Dame',
        'author_first_name': 'Victor',
        'author_last_name': 'Hugo',
        'publisher_name': 'Zahar',
        'pages': 624,
        'isbn': '9788537813584',
        'published_date': None,
        'cover_url': 'https://img.travessa.com.br/livro/GR/57/57903a73-eef1-408b-89ca-cb64b7f60991.jpg',
    },
    {
        'title': 'Em Algum Lugar nas Estrelas',
        'author_first_name': 'Clare',
        'author_last_name': 'Vanderpool',
        'publisher_name': 'DarkSide Books',
        'pages': 288,
        'isbn': '9788566636833',
        'published_date': None,
        'cover_url': 'https://darkside.blog.br/wp-content/uploads/2019/03/em-algum-lugar-nas-estrelas.jpg',
    },
    {
        'title': 'Alucinadamente Feliz',
        'author_first_name': 'Jenny',
        'author_last_name': 'Lawson',
        'publisher_name': 'Intrínseca',
        'pages': 352,
        'isbn': '9788580579314',
        'published_date': '2016-04-18',
        'cover_url': 'https://intrinseca.com.br/wp-content/uploads/2025/04/Capa_AlucinadamenteFeliz_G.jpg',
    },
    {
        'title': 'A Biblioteca da Meia-Noite',
        'author_first_name': 'Matt',
        'author_last_name': 'Haig',
        'publisher_name': 'Bertrand Brasil',
        'pages': 308,
        'isbn': '9786558380542',
        'published_date': None,
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9786558380542-L.jpg',
    },
    {
        'title': 'Quando as Mulheres Governavam o Mundo',
        'author_first_name': 'Maureen',
        'author_last_name': 'Quilligan',
        'publisher_name': 'Vestígio',
        'pages': 304,
        'isbn': '9786586551662',
        'published_date': '2022-06-06',
        'cover_url': 'https://grupoautentica.f1cdn.com.br/view/1080/1080/false/true/940.jpg?OTQwLQ==',
    },
    {
        'title': 'O Sol é Para Todos',
        'author_first_name': 'Harper',
        'author_last_name': 'Lee',
        'publisher_name': 'José Olympio',
        'pages': 349,
        'isbn': '9788503009492',
        'published_date': '2006-10-10',
        'cover_url': 'https://covers.openlibrary.org/b/isbn/9788503009492-L.jpg',
    },
    {
        'title': 'Senhora',
        'author_first_name': 'José',
        'author_last_name': 'de Alencar',
        'publisher_name': 'Ática',
        'pages': 262,
        'isbn': '9788508145591',
        'published_date': None,
        'cover_url': 'https://img.travessa.com.br/livro/GR/68/68b19915-2b58-4e1c-99e0-fc778f3abb7c.jpg',
    },
    {
        'title': 'Um Teto para Dois',
        'author_first_name': 'Beth',
        'author_last_name': "O'Leary",
        'publisher_name': 'Intrínseca',
        'pages': 400,
        'isbn': '9788551005415',
        'published_date': None,
        'cover_url': 'https://img.travessa.com.br/livro/GR/ab/abbb6378-ab1f-46f0-a0f0-16df31916773.jpg',
    },
    {
        'title': 'Alice: Edição Comentada e Ilustrada',
        'author_first_name': 'Lewis',
        'author_last_name': 'Carroll',
        'publisher_name': 'Companhia das Letras (Clássicos Zahar)',
        'pages': 416,
        'isbn': '9788537808269',
        'published_date': '2013-09-23',
        'cover_url': 'https://cdl-static.s3-sa-east-1.amazonaws.com/covers/gg/9788537808269/alice-edicao-comentada-e-ilustrada-com-traducao-de-maria-luiza-borges-vencedora-do-premio-jabuti.jpg',
    },
    {
        'title': 'A Menina que Roubava Livros',
        'author_first_name': 'Markus',
        'author_last_name': 'Zusak',
        'publisher_name': 'Intrínseca',
        'pages': 480,
        'isbn': '9788580574517',
        'published_date': '2014-01-06',
        'cover_url': 'https://intrinseca.com.br/wp-content/uploads/2025/04/capa-filme-a-menina-139-X-208.jpg',
    },
    {
        'title': 'A Pequena Loja de Venenos',
        'author_first_name': 'Sarah',
        'author_last_name': 'Penner',
        'publisher_name': 'HarperCollins Brasil',
        'pages': 320,
        'isbn': '9786555113747',
        'published_date': None,
        'cover_url': 'https://img.travessa.com.br/livro/GR/2c/2ccaa6d6-622b-44a1-83ce-270bffefdcd8.jpg',
    },
    {
        'title': 'Amor de Redenção',
        'author_first_name': 'Francine',
        'author_last_name': 'Rivers',
        'publisher_name': 'Verus',
        'pages': 468,
        'isbn': '9788576860884',
        'published_date': None,
        'cover_url': 'https://img.travessa.com.br/livro/GR/c3/c310221d-69e4-447d-b14e-6fcb8a83ad1c.jpg',
    },
    {
        'title': 'O Príncipe e a Costureira',
        'author_first_name': 'Jen',
        'author_last_name': 'Wang',
        'publisher_name': 'Darkside',
        'pages': 304,
        'isbn': '9786555980103',
        'published_date': None,
        'cover_url': 'https://img.travessa.com.br/livro/GR/91/915584a5-f7ee-4228-92a3-d5596dc210d7.jpg',
    },
    {
        'title': 'Flores para Algernon',
        'author_first_name': 'Daniel',
        'author_last_name': 'Keyes',
        'publisher_name': 'Aleph',
        'pages': 288,
        'isbn': '9788576573937',
        'published_date': '2018-07-10',
        'cover_url': 'https://aleph.com.br/cdn/shop/files/alp_testecapas_700x1000_FloresparaAlgernon.png?v=1714080956',
    },
    {
        'title': 'O Pequeno Príncipe',
        'author_first_name': 'Antoine',
        'author_last_name': 'de Saint-Exupéry',
        'publisher_name': 'Agir',
        'pages': 96,
        'isbn': '9788522031443',
        'published_date': None,
        'cover_url': 'https://img.travessa.com.br/livro/GR/75/7579c83b-7230-43ec-942d-9598573c8aa7.jpg',
    },
    {
        'title': 'Juízo Final',
        'author_first_name': 'Sidney',
        'author_last_name': 'Sheldon',
        'publisher_name': 'Record',
        'pages': 400,
        'isbn': '9788501094353',
        'published_date': '2011-10-31',
        'cover_url': 'https://www.record.com.br/cdn/shop/files/abac74ba4f271bfbc82f8d7c63be1f6e_548db5b5-f8e8-4acd-849e-388948b41d57.jpg',
    },
    {
        'title': 'Basta Um',
        'author_first_name': 'Flora',
        'author_last_name': 'Nwapa',
        'publisher_name': 'Roça Nova',
        'pages': 192,
        'isbn': '9786587796253',
        'published_date': '2023-06-01',
        'cover_url': None,
    },
    {
        'title': 'Phantastes',
        'author_first_name': 'George',
        'author_last_name': 'MacDonald',
        'publisher_name': 'Principis',
        'pages': 256,
        'isbn': '9786555526851',
        'published_date': None,
        'cover_url': 'https://img.travessa.com.br/livro/GR/c8/c8366e9c-7842-4638-857f-f90a7eaab1d8.jpg',
    },
    {
        'title': 'O Silêncio das Mulheres - Edição de Luxo',
        'author_first_name': 'Pat',
        'author_last_name': 'Barker',
        'publisher_name': 'Excelsior',
        'pages': 304,
        'isbn': '9786587435640',
        'published_date': None,
        'cover_url': 'https://cdn.awsli.com.br/600x450/1304/1304678/produto/149022830/769a35350a.jpg',
    },
    {
        'title': 'Robinson Crusoé',
        'author_first_name': 'Daniel',
        'author_last_name': 'Defoe',
        'publisher_name': 'Penguin-Companhia das Letras',
        'pages': 408,
        'isbn': '9788563560414',
        'published_date': '2012-05-02',
        'cover_url': 'https://cdl-static.s3-sa-east-1.amazonaws.com/covers/p/9788563560414/robinson-crusoe-traducao-de-sergio-flaksman-obra-prima-do-romance-de-aventura.jpg',
    },
    {
        'title': 'Verity',
        'author_first_name': 'Colleen',
        'author_last_name': 'Hoover',
        'publisher_name': 'Galera Record',
        'pages': 320,
        'isbn': '9788501117847',
        'published_date': None,
        'cover_url': 'https://www.record.com.br/cdn/shop/files/d714a333a0c7d64404774020856088c2.jpg?v=1784603948',
    },
    {
        'title': 'O Clube do Livro do Fim da Vida',
        'author_first_name': 'Will',
        'author_last_name': 'Schwalbe',
        'publisher_name': 'Objetiva',
        'pages': 296,
        'isbn': '9788539004997',
        'published_date': '2013-07-22',
        'cover_url': 'https://cdl-static.s3-sa-east-1.amazonaws.com/covers/gg/9788539004997/o-clube-do-livro-do-fim-da-vida.jpg',
    },
    {
        'title': 'Os Sete Maridos de Evelyn Hugo',
        'author_first_name': 'Taylor Jenkins',
        'author_last_name': 'Reid',
        'publisher_name': 'Paralela',
        'pages': 360,
        'isbn': '9788584391509',
        'published_date': '2019-10-21',
        'cover_url': 'https://cdl-static.s3-sa-east-1.amazonaws.com/covers/p/9788584391509/os-sete-maridos-de-evelyn-hugo.jpg',
    },
    {
        'title': 'A Fantástica Vida Breve de Oscar Wao',
        'author_first_name': 'Junot',
        'author_last_name': 'Díaz',
        'publisher_name': 'Record',
        'pages': 308,
        'isbn': '9786555873658',
        'published_date': '2022-04-18',
        'cover_url': 'https://www.record.com.br/cdn/shop/files/310c8b6548a6a5a84b2e344c2be5198b_1e91fbf5-9672-4a2c-aacf-d16410822a28.jpg?v=1778326617',
    },
    {
        'title': 'O Retorno',
        'author_first_name': 'Nicholas',
        'author_last_name': 'Sparks',
        'publisher_name': 'Arqueiro',
        'pages': 288,
        'isbn': '9786555650457',
        'published_date': '2020-11-27',
        'cover_url': 'https://img.travessa.com.br/livro/GR/1e/1e7703f4-26d2-42fc-a402-147bd20c526c.jpg',
    },
    {
        'title': 'Uma Segunda Chance',
        'author_first_name': 'Colleen',
        'author_last_name': 'Hoover',
        'publisher_name': 'Galera Record',
        'pages': 368,
        'isbn': '9786559811298',
        'published_date': '2022-05-31',
        'cover_url': 'https://img.travessa.com.br/livro/GR/35/35fc3cca-c511-4567-a45f-b49da9762296.jpg',
    },
    {
        'title': 'P.S. Eu Te Amo',
        'author_first_name': 'Cecelia',
        'author_last_name': 'Ahern',
        'publisher_name': 'Novo Conceito',
        'pages': 368,
        'isbn': '9788581630625',
        'published_date': '2020-06-29',
        'cover_url': 'https://s3.us-west-2.amazonaws.com/sgs.wpengine/buobooks1/wp-content/uploads/2020/06/Screen-Shot-2020-06-29-at-7.40.28-PM.png',
    },
    {
        'title': 'Mulheres que Correm com os Lobos',
        'author_first_name': 'Clarissa Pinkola',
        'author_last_name': 'Estés',
        'publisher_name': 'Rocco',
        'pages': 600,
        'isbn': '9788532529787',
        'published_date': None,
        'cover_url': 'https://rocco.com.br/wp-content/uploads/2022/12/9788532529787.jpg',
    },
    {
        'title': 'A Vila dos Tecidos',
        'author_first_name': 'Anne',
        'author_last_name': 'Jacobs',
        'publisher_name': 'Arqueiro',
        'pages': 512,
        'isbn': '9786555655049',
        'published_date': '2023-06-13',
        'cover_url': 'https://img.travessa.com.br/livro/GR/ca/ca81dafa-0ddc-45c5-aa25-7b792cad6f7d.jpg',
    },
    {
        'title': 'A Livraria dos Achados e Perdidos',
        'author_first_name': 'Susan',
        'author_last_name': 'Wiggs',
        'publisher_name': 'Harlequin',
        'pages': 368,
        'isbn': '9786587721132',
        'published_date': '2020-11-16',
        'cover_url': 'https://img.travessa.com.br/livro/GR/f7/f75c0e92-b5dc-47b5-9c10-f2db7f1fa653.jpg',
    },
    {
        'title': 'A Sombra do Vento',
        'author_first_name': 'Carlos Ruiz',
        'author_last_name': 'Zafón',
        'publisher_name': 'Suma',
        'pages': 464,
        'isbn': '9788556510341',
        'published_date': '2017-05-26',
        'cover_url': 'https://cdl-static.s3-sa-east-1.amazonaws.com/covers/gg/9788556510341/a-sombra-do-vento.jpg',
    },
    {
        'title': 'O Plantador de Abóboras',
        'author_first_name': 'Luís',
        'author_last_name': 'Cardoso',
        'publisher_name': 'Todavia',
        'pages': 160,
        'isbn': '9786556922737',
        'published_date': None,
        'cover_url': 'https://img.travessa.com.br/livro/GR/e8/e86eda2a-2079-4ad6-a56a-2cd69143ccdc.jpg',
    },
]
